# This is a config synced from rom-rb/template-gem repo

sources:
  - repo: rom-rb/template-gem
    sync:
      - ".repobot.yml.erb"
      - ".devtools/templates/*.sync:${{dir}}/${{name}}"
      - ".github/**/*.*"
      - "spec/support/*"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "CODEOWNERS"
      - "LICENSE.erb"
      - "README.erb"
      - "Gemfile.devtools"
      - ".rspec"
      - ".rubocop.yml"
  - repo: repobot-app/workflows
    sync:
      - ".github/workflows/*.yml"
